CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(512) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    request_description VARCHAR(512) NOT NULL,
    requestor BIGINT REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    request_created date
    );

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    item_description VARCHAR(512) NOT NULL,
    item_available boolean NOT NULL,
    item_owner BIGINT REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    item_request BIGINT REFERENCES requests (request_id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS booking_statuses (
    booking_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    booking_status_name VARCHAR(100)
    );

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    booking_start date,
    booking_end date,
    item BIGINT REFERENCES items (item_id) ON DELETE CASCADE ON UPDATE CASCADE,
    booker BIGINT REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    booking_status VARCHAR(100)
    );